version: "3.8"

services:
  inventory-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: inventory
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - inventory-db-data:/var/lib/mysql
    networks:
      - microservices

  order-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: orders
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - order-db-data:/var/lib/mysql
    networks:
      - microservices

  discovery-service:
    image: saitejajambarapu/discovery-service:latest
    ports:
      - "8761:8761"
    networks:
      - microservices

  config-server:
    image: saitejajambarapu/config-server
#    depends_on:
#      - discovery-service
    networks:
      - microservices

  inventory-service:
    image: saitejajambarapu/inventory-service
    depends_on:
      - discovery-service
      - config-server
      - inventory-db
    networks:
      - microservices

  orders-service:
    image: saitejajambarapu/orders-service
    depends_on:
      - discovery-service
      - config-server
      - order-db
    networks:
      - microservices

  api-gateway:
    image: saitejajambarapu/api-gateway
    ports:
      - "8083:8083"
    depends_on:
      - discovery-service
      - config-server
      - inventory-service
      - orders-service
    networks:
      - microservices

volumes:
  inventory-db-data:
  order-db-data:

networks:
  microservices:
