spring.application.name: config-server

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/saitejajambarapu/Config-Server
          username: saitejajambarapu
          password: XXXXXXXXX
          default-label: main

server:
  port: 8888

eureka:
  client:
#    service-url:
#      defaultZone: http://discovery-service:8761/eureka
    enabled: false
